CC-1455: Add a note for \n in Interpreter - Scanning: Whitespace #er2
codecrafters-io/build-your-own-interpreter pull request #50
Opened 2024-10-10 01:24 UTC by andy1li

2024-10-14 11:22 UTC, rohitpaulk commented on course-definition.yml
> +      - The test cases will be multi-line, so you will need to handle newline characters (`\n`) correctly.
@andy1li we try to keep notes to under 3 items to avoid cognitive overload. Is there a way we can instead fit this into the other instructions that are already present and mention space/tab?

2024-10-14 11:23 UTC, rohitpaulk requested changes
Note added

2024-10-15 02:15 UTC, andy1li commented
@rohitpaulk I encountered a linting error, so upgraded the version for rust-tools in course-sdk: https://github.com/codecrafters-io/course-sdk/pull/45/files.

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/5ba991d3-dbca-4363-b986-a9371f58cf16">

2024-10-15 15:53 UTC, rohitpaulk approved these changes

2024-10-15 16:35 UTC, merged